services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: practical-ai-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    restart: always

